### ISSUE TITLE
to_xarray() error in online lab

### ISSUE THREAD

**Issue by SF-N** [climet-eu/compression-lab-notebooks#12] opened 2024-09-04 13:03 UTC
When running the following code (from ecmwfapi.ipynb on the hplp_experiment branch):
```python
import earthkit
print(earthkit.__version__)


data = earthkit.data.from_source("file", "data.grib")
da = data[0:]
da_x = da.to_xarray()
display(da_x)
data_vars = list(da_x.data_vars)
```
in the online lab, I am getting the following error: 
```
---------------------------------------------------------------------------
FunctionalityNotEnabledError              Traceback (most recent call last)
Cell In[10], line 7
      5 data = earthkit.data.from_source("file", "data.grib")
      6 da = data[0:]
----> 7 da_x = da.to_xarray()
      8 display(da_x)
      9 data_vars = list(da_x.data_vars)

File /lib/python3.11/site-packages/earthkit/data/readers/grib/xarray.py:138, in XarrayMixIn.to_xarray(self, **kwargs)
    125 default.update(self.xarray_open_dataset_kwargs())
    127 xarray_open_dataset_kwargs.update(
    128     Kwargs(
    129         user=user_xarray_open_dataset_kwargs,
   (...)
    135     )
    136 )
--> 138 result = xr.open_dataset(
    139     IndexWrapperForCfGrib(self, ignore_keys=ignore_keys),
    140     **xarray_open_dataset_kwargs,
    141 )
    143 return result

File /lib/python3.11/site-packages/xarray/backends/api.py:572, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)
    560 decoders = _resolve_decoders_kwargs(
    561     decode_cf,
    562     open_backend_dataset_parameters=backend.open_dataset_parameters,
   (...)
    568     decode_coords=decode_coords,
    569 )
    571 overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 572 backend_ds = backend.open_dataset(
    573     filename_or_obj,
    574     drop_variables=drop_variables,
    575     **decoders,
    576     **kwargs,
    577 )
    578 ds = _dataset_from_backend_dataset(
    579     backend_ds,
    580     filename_or_obj,
   (...)
    590     **kwargs,
    591 )
    592 return ds

File /lib/python3.11/site-packages/cfgrib/xarray_plugin.py:108, in CfGribBackend.open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, lock, indexpath, filter_by_keys, read_keys, encode_cf, squeeze, time_dims, errors, extra_coords)
     87 def open_dataset(
     88     self,
     89     filename_or_obj: T.Union[str, abc.MappingFieldset[T.Any, abc.Field]],
   (...)
    106     extra_coords: T.Dict[str, str] = {},
    107 ) -> xr.Dataset:
--> 108     store = CfGribDataStore(
    109         filename_or_obj,
    110         indexpath=indexpath,
    111         filter_by_keys=filter_by_keys,
    112         read_keys=read_keys,
    113         encode_cf=encode_cf,
    114         squeeze=squeeze,
    115         time_dims=time_dims,
    116         lock=lock,
    117         errors=errors,
    118         extra_coords=extra_coords,
    119     )
    120     with xr.core.utils.close_on_error(store):
    121         vars, attrs = store.load()  # type: ignore

File /lib/python3.11/site-packages/cfgrib/xarray_plugin.py:40, in CfGribDataStore.__init__(self, filename, lock, **backend_kwargs)
     38 else:
     39     opener = dataset.open_fieldset
---> 40 self.ds = opener(filename, **backend_kwargs)

File /lib/python3.11/site-packages/cfgrib/dataset.py:760, in open_fieldset(fieldset, indexpath, filter_by_keys, read_keys, time_dims, extra_coords, computed_keys, log, **kwargs)
    758 index = messages.FieldsetIndex.from_fieldset(fieldset, index_keys, computed_keys)
    759 filtered_index = index.subindex(filter_by_keys)
--> 760 return open_from_index(filtered_index, read_keys, time_dims, extra_coords, **kwargs)

File /lib/python3.11/site-packages/cfgrib/dataset.py:736, in open_from_index(index, read_keys, time_dims, extra_coords, **kwargs)
    729 def open_from_index(
    730     index: abc.Index[T.Any, abc.Field],
    731     read_keys: T.Sequence[str] = (),
   (...)
    734     **kwargs: T.Any,
    735 ) -> Dataset:
--> 736     dimensions, variables, attributes, encoding = build_dataset_components(
    737         index, read_keys=read_keys, time_dims=time_dims, extra_coords=extra_coords, **kwargs
    738     )
    739     return Dataset(dimensions, variables, attributes, encoding)

File /lib/python3.11/site-packages/cfgrib/dataset.py:663, in build_dataset_components(index, errors, encode_cf, squeeze, log, read_keys, time_dims, extra_coords)
    661 var_index = index.subindex(paramId=param_id)
    662 try:
--> 663     dims, data_var, coord_vars = build_variable_components(
    664         var_index,
    665         encode_cf,
    666         filter_by_keys,
    667         errors=errors,
    668         squeeze=squeeze,
    669         read_keys=read_keys,
    670         time_dims=time_dims,
    671         extra_coords=extra_coords,
    672     )
    673 except DatasetBuildError as ex:
    674     # NOTE: When a variable has more than one value for an attribute we need to raise all
    675     #   the values in the file, not just the ones associated with that variable. See #54.
    676     key = ex.args[1]

File /lib/python3.11/site-packages/cfgrib/dataset.py:573, in build_variable_components(index, encode_cf, filter_by_keys, log, errors, squeeze, read_keys, time_dims, extra_coords)
    571     header_indexes, message_ids = next(iter(offsets.items()))
    572     message = index.get_field(message_ids[0])
--> 573     values = get_values_in_order(message, np.empty(shape)[header_indexes].shape)
    574     dtype = values.dtype
    575 else:
    576     # Fall back to a reasonable default dtype

File /lib/python3.11/site-packages/cfgrib/dataset.py:315, in get_values_in_order(message, shape)
    312 def get_values_in_order(message, shape):
    313     # type: (abc.Field, T.Tuple[int]) -> np.ndarray
    314     # inform the data provider to return missing values as missing_value
--> 315     values = message["values"]
    316     if message.get("alternativeRowScanning", False):
    317         values = values.copy().reshape(shape)

File /lib/python3.11/site-packages/cfgrib/messages.py:246, in ComputedKeysAdapter.__getitem__(self, item)
    244     return getter(self)
    245 else:
--> 246     return self.context[item]

File /lib/python3.11/site-packages/earthkit/data/readers/grib/xarray.py:28, in ItemWrapperForCfGrib.__getitem__(self, n)
     26     return None
     27 if n == "values":
---> 28     return self.item.values
     29 return self.item.metadata(n)

File /lib/python3.11/site-packages/earthkit/data/core/fieldlist.py:107, in Field.values(self)
    102 @property
    103 def values(self):
    104     r"""array-like: Get the values stored in the field as a 1D array. The array type
    105     is defined by :attr:`array_backend`
    106     """
--> 107     v = self._to_array(self._values(), source_backend=self.raw_values_backend)
    108     if len(v.shape) != 1:
    109         n = math.prod(v.shape)

File /lib/python3.11/site-packages/earthkit/data/readers/grib/codes.py:264, in GribField._values(self, dtype)
    263 def _values(self, dtype=None):
--> 264     return self.handle.get_values(dtype=dtype)

File /lib/python3.11/site-packages/earthkit/data/readers/grib/codes.py:206, in GribCodesHandle.get_values(self, dtype)
    204 def get_values(self, dtype=None):
    205     eccodes.codes_set(self._handle, "missingValue", CodesHandle.MISSING_VALUE)
--> 206     vals = VALUE_ACCESSOR.get(self._handle, dtype=dtype)
    207     if self.get_long("bitmapPresent"):
    208         vals[vals == CodesHandle.MISSING_VALUE] = np.nan

File /lib/python3.11/site-packages/earthkit/data/readers/grib/codes.py:64, in GribCodesValueAccessor.get(self, handle, dtype)
     62     return eccodes.codes_get_array(handle, self.KEY, ktype=dtype)
     63 else:
---> 64     return super().get(handle, dtype=dtype)

File /lib/python3.11/site-packages/earthkit/data/readers/grib/codes.py:47, in GribCodesFloatArrayAccessor.get(self, handle, dtype)
     46 def get(self, handle, dtype=None):
---> 47     v = eccodes.codes_get_array(handle, self.KEY)
     48     if dtype is not None:
     49         return v.astype(dtype)

File /lib/python3.11/site-packages/gribapi/gribapi.py:2028, in grib_get_array(msgid, key, ktype)
   2026     result = grib_get_long_array(msgid, key)
   2027 elif ktype is float or ktype is np.float64:
-> 2028     result = grib_get_double_array(msgid, key)
   2029 elif ktype is np.float32:
   2030     result = grib_get_float_array(msgid, key)

File /lib/python3.11/site-packages/gribapi/gribapi.py:1196, in grib_get_double_array(msgid, key)
   1194 vals_p = ffi.cast("double *", arr.ctypes.data)
   1195 err = lib.grib_get_double_array(h, key.encode(ENC), vals_p, length_p)
-> 1196 GRIB_CHECK(err)
   1197 return arr

File /lib/python3.11/site-packages/gribapi/gribapi.py:226, in GRIB_CHECK(errid)
    218 """
    219 Utility function checking the ecCodes error code and raising
    220 an error if that was set.
   (...)
    223 @exception CodesInternalError
    224 """
    225 if errid:
--> 226     errors.raise_grib_error(errid)

File /lib/python3.11/site-packages/gribapi/errors.py:381, in raise_grib_error(errid)
    377 def raise_grib_error(errid):
    378     """
    379     Raise the GribInternalError corresponding to ``errid``.
    380     """
--> 381     raise ERROR_MAP[errid](errid)

FunctionalityNotEnabledError: Functionality not enabled
```
It runs fine locally, and locally I have earthkit version 0.6.2 installed. In the online lab it seems to be the same. 
Is this something on our side or should I talk to the earthkit developers?

**Comment by juntyr** [comment] 2024-09-23 11:31
This is an issue with `eccodes`. For the online lab, we currently build it with the following options:

```
-DENABLE_NETCDF=OFF -DENABLE_JPG=OFF -DENABLE_PNG=OFF -DENABLE_AEC=OFF -DENABLE_FORTRAN=OFF
```

Do you have an idea which one would be needed to load this dataset (this is probably a question for one of the eccodes maintainers). I can then try to build eccodes with that option enabled

**Comment by juntyr** [comment] 2024-10-01 08:37
The online lab now builds eccodes with JPG, PNG, and AEC support all turned on. @SF-N could you please check if the issue is now fixed?

**Comment by SF-N** [comment] 2024-10-02 13:03
Now I am getting the following error while it still works in the local notebook:

```
Unknown file type, no reader available. path=data_ml_O400.grib magic=b'\x00\x00\x00>\xc1,[\x80\x00\x00\x00>\xc1[/](https://lab.climet.eu/lab?repo=https%3A%2F%2Fgithub.com%2Fclimet-eu%2Fcompression-lab-notebooks&urlpath=tree%2Fcompression-lab-notebooks%2Flab.ipynb&branch=main)\xeb\x80\x00\x00\x00>\xc1[/](https://lab.climet.eu/lab?repo=https%3A%2F%2Fgithub.com%2Fclimet-eu%2Fcompression-lab-notebooks&urlpath=tree%2Fcompression-lab-notebooks%2Flab.ipynb&branch=main)+\x80\x00\x00\x00>\xc1*\xeb\x80\x00\x00\x00>\xc1%\x9b\x80\x00\x00\x00>\xc1"\xcb\x80\x00\x00\x00>\xc1$K\x80\x00\x00\x00>\xc1%[\x80' content_type=None

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 6
      2 print(earthkit.__version__)
      5 data = earthkit.data.from_source("file", "data_ml_O400.grib")
----> 6 da = data[0:]
      7 da_x = da.to_xarray()
      8 display(da_x)

File /lib/python3.11/site-packages/earthkit/data/sources/file.py:108, in FileSource.__getitem__(self, n)
    107 def __getitem__(self, n):
--> 108     return self._reader[n]

TypeError: 'UnknownReader' object is not subscriptable```

**Comment by juntyr** [comment] 2024-10-02 13:48
Ok, so I think we’re now blocked on the same issue as I had to hack around in https://github.com/climet-eu/compression-lab-notebooks/issues/7#issuecomment-2385129121. Can you try that workaround? This is an issue with earthkit not recognising some GRIB files that the earthkit developers have to fix, perhaps you can push the issue

**Comment by juntyr** [comment] 2024-10-02 13:48
Cc https://github.com/ecmwf/earthkit-data/issues/123#issuecomment-2385137248

**Comment by juntyr** [comment] 2024-10-09 06:46
The following notebook now works in the online lab and has all the dataset loading and plotting: https://gist.github.com/juntyr/a3f5459735653a32295fec64a8edc1d1

**Closed as completed by juntyr** 2024-10-09 06:46 UTC
